/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TeaPlus API
 * OpenAPI spec version: 0.0.1
 */

export interface AuthResponse {
    /** Access token used for authorization */
    accessToken: string;
}
