/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TeaPlus API
 * OpenAPI spec version: 0.0.1
 */

export interface InitPaymentResponse {
    /** Internal transaction ID */
    id: string;
    /** Redirect URL for external providers (Stripe, Crypto, Stars) */
    url?: string;
    /** Confirmation token for YooKassa Embedded Widget. Used on the frontend to render the payment form directly on the site instead of redirecting. */
    token?: string;
}
