/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TeaPlus API
 * OpenAPI spec version: 0.0.1
 */
import type { InitPaymentRequestBillingPeriod } from './initPaymentRequestBillingPeriod';
import type { InitPaymentRequestProvider } from './initPaymentRequestProvider';

export interface InitPaymentRequest {
    /** ID of the selected subscription plan */
    planId: string;
    /** Subscription billing period (monthly or yearly) */
    billingPeriod: InitPaymentRequestBillingPeriod;
    /** Payment provider */
    provider: InitPaymentRequestProvider;
    /** Token for YOOKASSA checkout.js (optional, only required for YOOKASSA) */
    paymentToken?: string;
}
