/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TeaPlus API
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentDetailsResponseBillingPeriod } from './paymentDetailsResponseBillingPeriod';
import type { SubscriptionInfo } from './subscriptionInfo';

export interface PaymentDetailsResponse {
    /** Unique identifier of the transaction */
    id: string;
    /** Billing period selected for the subscription */
    billingPeriod: PaymentDetailsResponseBillingPeriod;
    /** Subscription information including selected plan details */
    subscription: SubscriptionInfo;
}
