/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TeaPlus API
 * OpenAPI spec version: 0.0.1
 */

/**
 * Billing period selected for the subscription
 */
export type PaymentDetailsResponseBillingPeriod = typeof PaymentDetailsResponseBillingPeriod[keyof typeof PaymentDetailsResponseBillingPeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentDetailsResponseBillingPeriod = {
    MONTHLY: 'MONTHLY',
    YEARLY: 'YEARLY',
} as const;
