/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TeaPlus API
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentHistoryResponseProvider } from './paymentHistoryResponseProvider';
import type { PaymentHistoryResponseStatus } from './paymentHistoryResponseStatus';

export interface PaymentHistoryResponse {
    /** Unique transaction identifier */
    id: string;
    /** Transaction created at */
    createdAt: string;
    /** Subscription plan name */
    plan: string;
    /** Amount of the transaction */
    amount: number;
    /** Payment provideer used for the transaction */
    provider: PaymentHistoryResponseProvider;
    /** Transaction status */
    status: PaymentHistoryResponseStatus;
}
