/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TeaPlus API
 * OpenAPI spec version: 0.0.1
 */
import type { PlanInfo } from './planInfo';

export interface SubscriptionInfo {
    /** Detailed information about the selected plan */
    plan: PlanInfo;
}
