import type { Metadata } from 'next'
import { Geist } from 'next/font/google'

import './globals.css'
import { Providers } from './providers'

const geist = Geist({
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
                                       children
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='ru'>
        <body className={`${geist.className} antialiased`}>
        <Providers>{children}</Providers>
        </body>
        </html>
    )
}
